<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Admin extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $guard = 'admin';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'phone',
        'role',
        'union_id',
        'ward_id',
        'designation',
        'address',
        'profile_photo',
        'status',
        'last_login_at',
        'last_login_ip',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'last_login_at' => 'datetime',
        'status' => 'boolean',
    ];

    /**
     * Get the user's full name.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return $this->name;
    }

    /**
     * Relationship with Union
     */
    public function union()
    {
        return $this->belongsTo(Union::class);
    }

    /**
     * Relationship with Ward
     */
    public function ward()
    {
        return $this->belongsTo(Ward::class);
    }

    /**
     * Relationship with Applications
     */
    public function applications()
    {
        return $this->hasMany(Application::class);
    }

    /**
     * Relationship with Invoices through Applications
     */
    public function invoices()
    {
        return $this->hasManyThrough(Invoice::class, Application::class);
    }

    /**
     * Scope for active admins
     */
    public function scopeActive($query)
    {
        return $query->where('status', true);
    }

    /**
     * Scope for admins by role
     */
    public function scopeByRole($query, $role)
    {
        return $query->where('role', $role);
    }

    /**
     * Get the total revenue generated by admin
     */
    public function getTotalRevenueAttribute()
    {
        return $this->invoices()
            ->where('payment_status', 'paid')
            ->sum('amount');
    }

    /**
     * Get the total applications count
     */
    public function getApplicationsCountAttribute()
    {
        return $this->applications()->count();
    }

    /**
     * Get the pending applications count
     */
    public function getPendingApplicationsAttribute()
    {
        return $this->applications()->where('status', 'pending')->count();
    }

    /**
     * Get the approved applications count
     */
    public function getApprovedApplicationsAttribute()
    {
        return $this->applications()->where('status', 'approved')->count();
    }

    /**
     * Update last login info
     */
    public function updateLastLogin()
    {
        $this->update([
            'last_login_at' => now(),
            'last_login_ip' => request()->ip(),
        ]);
    }

    /**
     * Check if admin is super admin
     */
    public function isSuperAdmin()
    {
        return $this->role === 'super_admin';
    }

    /**
     * Check if admin is regular admin
     */
    public function isRegularAdmin()
    {
        return $this->role === 'admin';
    }

    /**
     * Check if admin is secretary
     */
    public function isSecretary()
    {
        return $this->role === 'secretary';
    }
}